---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    image: node:lts
    commands:
      - cd frontend
      - yarn ci

  - name: lint
    image: node:lts
    commands:
      - cd frontend
      - yarn lint
    depends_on:
      - install

  - name: unit-test
    image: node:lts
    commands:
      - cd frontend
      - yarn test:unit --coverage
    depends_on:
      - lint

  - name: e2e-test-chrome
    image: cypress/included:10.4.0
    commands:
      - cd frontend
      - cypress info
      - yarn test:e2e:ci:chrome
    depends_on:
      - lint

  - name: e2e-test-firefox
    image: cypress/included:10.4.0
    commands:
      - cd frontend
      - cypress info
      - yarn test:e2e:ci:firefox
    depends_on:
      - lint

  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      level: DEBUG
      showProfiling: true
    depends_on:
      - unit-test
      - e2e-test-chrome
      - e2e-test-firefox

  - name: build
    image: node:lts
    commands:
      - cd frontend
      - yarn build
    environment:
      VITE_TASK_ENDPOINT:
        from_secret: VITE_TASK_ENDPOINT
      VITE_IMPRINT_CITY:
        from_secret: VITE_IMPRINT_CITY
      VITE_IMPRINT_EMAIL:
        from_secret: VITE_IMPRINT_EMAIL
      VITE_IMPRINT_NAME:
        from_secret: VITE_IMPRINT_NAME
      VITE_IMPRINT_POSTAL_CODE:
        from_secret: VITE_IMPRINT_POSTAL_CODE
      VITE_IMPRINT_STREET:
        from_secret: VITE_IMPRINT_STREET
    depends_on:
      - code-analysis

  - name: deploy-docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: production-stage
      repo: michigg/web-sense
      auto_tag: true
      dockerfile: frontend/Dockerfile
      context: frontend
    when:
      branch:
        - main
      event:
        - tag
        - push
    depends_on:
      - build

  - name: publish-github
    image: plugins/gh-pages
    commands:
      - touch frontend/dist/.nojekyll
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      pages_directory: frontend/dist
    when:
      branch:
        - main
      event:
        - tag
        - push
    depends_on:
      - build

  - name: notify
    image: plugins/matrix
    settings:
      homeserver:
        from_secret: matrix_homeserver
      roomid:
        from_secret: matrix_roomid
      userid:
        from_secret: matrix_userid
      accesstoken:
        from_secret: matrix_accesstoken
      template: >
        {{#success build.status}}
        ✅ {{repo.owner}}/{{repo.name}}  {{build.number}}
        {{else}}
        ❌ {{repo.owner}}/{{repo.name}} {{build.number}}
        {{/success}}
        depends_on:
        - deploy
    when:
      status:
        - success
        - failure
    depends_on:
      - deploy-docker
      - publish-github
      - build

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
