version: '3'

services:
  web:
    image: michigg/masterthesis:working-draft-0.18.4
    build: ./frontend
    ports:
      - 8081:80

  taskApi:
    image: michigg/masterthesis:working-draft-backend-0.18.4
    ports:
      - "8888:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/api:/api
