export enum ResultValueKey {
  CREATED_AT = 'CREATED_AT',
  QUATERNION = 'QUATERNION',
  FREQUENCY_ABSOLUTE_ORIENTATION_SENSOR = 'FREQUENCY_ABSOLUTE_ORIENT_SENSOR',
  REFERENCE_FRAME = 'REFERENCE_FRAME',
}
