@startuml
start
-> start app;
:PageTasks;
:PageTask start;
-> execute task;
:PageTaskExecution;
repeat
    :TaskStepActivity;
repeat while(all task steps not done?) is (yes) not (no)
:PageTaskFinished;
if (donate?) then
-> Yes;
else
-> No;
endif
:PageLogElement;
stop
@enduml
