@startuml
actor Human
participant CalibrationView
database CalibrationStore
database LocalDB
participant MicCalibrationService
participant AudioAnalysisService

Human --> CalibrationView: calibrate()
CalibrationView --> CalibrationStore: action:calibrate()
CalibrationStore --> MicCalibrationService: calibrate()
MicCalibrationService --> AudioAnalysisService: analyse()
AudioAnalysisService --> MicCalibrationService: AnalysisData
MicCalibrationService --> AudioAnalysisService: analyse()
AudioAnalysisService --> MicCalibrationService: AnalysisData
MicCalibrationService --> CalibrationStore: CalibrationData
CalibrationStore --> LocalDB: save(CalibrationData)
CalibrationStore --> CalibrationView: isCalibrated(true)
@enduml
