@startuml C4_Elements
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!include ICONURL/common.puml
!include ICONURL/devicons2/vuejs.puml
!include ICONURL/font-awesome-5/map.puml
!include ICONURL/govicons/user.puml
!include ICONURL/govicons/user_suit.puml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(contributor, "Contributor", "Accepts tasks, senses data", $sprite=user)
Person(task_manager, "Task Manager", "Creates tasks", $sprite=user_suit)
Person_Ext(consumer, "Consumer", "Retrieves sensed data", $sprite=user)

System(mcs, "Crowd Sensing System", "Web-based crowd sensing platform")
System_Ext(osm, "OSM", "Provides map data", $sprite=map)
System_Ext(datastore, "Crowd sensed data systems", "ThingsBoard or InfluxDB; Stores crowd sensed data and provides UI to display them")

Rel(contributor, mcs, "Uses application", "HTTPS")
Rel(task_manager, mcs, "Updates task configuration file", "")
Rel(consumer, datastore, "Shows contributed data", "HTTPS")
Rel_R(mcs, datastore, "Sends measurment data", "HTTPS")
Rel(mcs, osm, "Requests map data", "HTTPS")
@enduml
