@startuml C4_Elements
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!include ICONURL/common.puml
!include ICONURL/devicons2/vuejs.puml
!include ICONURL/devicons2/nginx_original.puml
!include ICONURL/font-awesome-5/map.puml
!include ICONURL/govicons/user.puml
!include ICONURL/govicons/user_suit.puml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(contributor, "Contributor", "Accepts tasks, senses data", $sprite=user)
Person(task_manager, "Task Manager", "Creates tasks", $sprite=user_suit)
Person_Ext(consumer, "Consumer", "Retrieves sensed data", $sprite=user)

System_Boundary(c1, "Mobile Crowd Sensing") {
    Container(mcs, "PWA", "Vue3", "Main interface of the crowd sensing system", $sprite=vuejs)
    Container(mcs_web_server, "Application Server", "Web Server", "Stores and delivers the pwa contents", $sprite=nginx_original)
    Container(mcs_backend, "API Server", "Web Server", "Stores and delivers the task configuration",$sprite=nginx_original)
}
System_Ext(osm, "OSM", "Provides map data", $sprite=map)
System_Ext(datastore, "Crowd sensed data systems", "ThingsBoard or InfluxDB; Stores crowd sensed data and provide UI to display them")

Rel(contributor, mcs, "Uses", "HTTPS")
Rel_R(task_manager, mcs_backend, "Updates task configuration file", "")
Rel(consumer, datastore, "Uses", "HTTPS")
Rel_R(mcs, datastore, "Sends donated data", "HTTPS")
Rel_L(mcs, osm, "Requests map data", "HTTPS")

Rel_D(mcs, mcs_web_server, "Requests app data", "HTTPS")
Rel_D(mcs, mcs_backend, "Requests task data", "HTTPS")
@enduml
